name: github-actions
run-name: GitHub Actions
on: [push]
jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js
      - uses: actions/setup-node@v3
        with: 
          node-version: '21'
       -name: install modules
       run: npm install
       -name: build project
       run: npm run build-only
      

   
