name: github-actions
run-name: GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  init:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [21]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{matrix.node}}
      - uses: actions/setup-node@v3
      with: 
       node-version: ${{matrix.node}}
       -name: install modules
       run: npm install
       -name: build project
       run: npm run build-only
      

   
